# Generated by Django 3.2.24 on 2024-02-21 22:37

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='format: not required, max_length=50', max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, help_text='format: not required, max_length=50', max_length=50, null=True, verbose_name='Last name')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(help_text='format: required, unique=True', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(help_text='format: required, max_length=100', max_length=100, verbose_name='Address line')),
                ('city', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='City')),
                ('country', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='Country')),
                ('county_region', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='County/Region')),
                ('zip_code', models.CharField(help_text='format: required, max_length=20', max_length=20, verbose_name='Zip code')),
                ('is_primary', models.BooleanField(default=False, help_text='format: not required', verbose_name='Primary')),
                ('phone_number', models.CharField(help_text='format: required, max_length=20', max_length=20, verbose_name='Phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('profile', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profile')),
            ],
        ),
    ]
