# Generated by Django 3.2.24 on 2024-02-28 00:21

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(help_text='format: required, max_length=50', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='profiles.profile', verbose_name='Profile'),
        ),
    ]
