# Generated by Django 5.0.3 on 2024-04-08 01:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
