# Generated by Django 3.2.24 on 2024-03-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='format: optional', max_length=500, null=True, verbose_name='Product Image URL'),
        ),
    ]
