# Generated by Django 5.0.3 on 2024-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20240314_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Check this box if the product is a best seller.', verbose_name='Is Best Seller'),
        ),
    ]
