# Generated by Django 5.0.3 on 2024-04-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='county_region',
        ),
    ]
