# Generated by Django 5.0.3 on 2024-07-02 18:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_total_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
